server:
  port: 8001
spring:
  application:
    name: gateway-web
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
    gateway:
      routes:
        - id: http_config_route
          uri: lb://nginx-http-config-manager
          predicates:
            - Path=/api/config/server/**
          filters:
            - StripPrefix=1
        - id: search_config_route
          uri: lb://nginx-config-search
          predicates:
            - Path=/api/search/**
          filters:
            - StripPrefix=1